---
title: "Premier League 2017-2018 Point Acculmulation"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
We've created some interactive plots using plotly! Since GitHub can't handle the JavaScript or html for this file, you can access the plot by clicking this link: 
```{r include=FALSE}
PointsTable <- read.csv("~/EPL Data/Clean Data/PointsTable17-18.csv")
#reshaping the Points Table for 2017-2018 for graphing purposes
PointsTable.long<- reshape(PointsTable[,2:31], varying=c("Week01","Week02", "Week03", "Week04", "Week05", "Week06", "Week07", "Week08","Week09", "Week10", "Week11", "Week12","Week13", "Week14", "Week15", "Week16", "Week17", "Week18","Week19", "Week20", "Week21", "Week22", "Week23", "Week24",
"Week25", "Week26", "Week27", "Week28", "Week29", "Week30"),                                 v.names='Week',timevar="Time",idvar="Teams",direction="long")

```


```{r, eval=FALSE, include=FALSE}
library(plotly)
#Comparing all 20 teams
a <- plot_ly(PointsTable.long, x = ~Time[Teams==1], y = ~Week[Teams==1], name = 'Arsenal', type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~Week[Teams==2], name = 'Bournemouth', mode = 'lines') %>%
  add_trace(y = ~Week[Teams==3], name = "Brighton", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==4], name = "Burnley", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==5], name = "Chelsea", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==6], name = "Crystal Palace", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==7], name = "Everton", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==8], name = "Huddersfield", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==9], name = "Leicester", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==10], name = "Liverpool", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==11], name = "Manchester City", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==12], name = "Manchester United", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==13], name = "Newcastle", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==14], name = "Southamptom", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==15], name = "Stoke", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==16], name = "Swansea", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==17], name = "Tottenham", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==18], name = "watford", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==19], name = "West Brom", mode = 'lines') %>%
  add_trace(y = ~Week[Teams==20], name = "West Ham", mode = 'lines') %>%
  layout(title = "Point Accumulation for 2017-2018 season", xaxis = list(title = "Week"), yaxis = list(title = "# of points"))
```

```{r, eval=FALSE, echo=FALSE}
a
```

https://plot.ly/~CClingain/1/